version: 2
jobs:
  build-publish-trigger:

    machine:
      enabled: true

    working_directory: ~/repo

    steps:
      - checkout
      - run:
          name: Build and test
          command: ./pipe_build_up_test.sh

workflows:
  version: 2
  build-publish-trigger:
    jobs:
      - build-publish-trigger:
          filters:
            branches:
              only:
                  - master
